import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClerkProvider,SignInButton,SignedOut,SignedIn,UserButton, SignOutButton } from "@clerk/nextjs";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <header>
        <SignedOut>
            <SignInButton/>
        </SignedOut>
        <SignedIn>
          <div className="flex justify-between m-2">
              <UserButton/>
              <SignOutButton/>
          </div>
            
        </SignedIn>


        
      </header>
        {children}
      </body>
    </html>
    </ClerkProvider>
  );
}
